{"uid":"461063ab82b5fd3c","name":"Test01: Log in to grafana using DB","fullName":"test_cases.test_cases_db.TestCasesDB#test_login_grafana","historyId":"b831385f8be5373e2699aa37dbb05c32","time":{"start":1726496777927,"stop":1726496777927,"duration":0},"description":"Log in to grafana using DB","descriptionHtml":"<p>Log in to grafana using DB</p>\n","status":"broken","statusMessage":"TypeError: WebDriver.__init__() got an unexpected keyword argument 'service'","statusTrace":"request = <SubRequest 'init_driver' for <Function test_login_grafana>>\n\n    @pytest.fixture(scope='class')\n    def init_driver(request):\n>       edriver = get_driver()\n\ntest_cases\\conftest.py:34: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\ntest_cases\\conftest.py:118: in get_driver\n    driver = get_chrome()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\n    def get_chrome():\n    \n        #chrome_driver = webdriver.Chrome(ChromeDriverManager().install())  #selenium 3.x\n        srv = Service(ChromeDriverManager().install())\n>       chrome_driver = selenium.webdriver.Chrome(service=srv)\nE       TypeError: WebDriver.__init__() got an unexpected keyword argument 'service'\n\ntest_cases\\conftest.py:144: TypeError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"init_database_connection","time":{"start":1726496777927,"stop":1726496780042,"duration":2115},"status":"passed","steps":[],"attachments":[],"parameters":[],"attachmentStep":false,"stepsCount":0,"hasContent":false,"shouldDisplayMessage":false,"attachmentsCount":0},{"name":"init_driver","time":{"start":1726496780042,"stop":1726496781386,"duration":1344},"status":"broken","statusMessage":"TypeError: WebDriver.__init__() got an unexpected keyword argument 'service'\n","statusTrace":"  File \"C:\\Automation\\test_automation_final_project\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Automation\\test_automation_final_project\\.venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Automation\\test_automation_final_project\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Automation\\test_automation_final_project\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1139, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Automation\\test_automation_final_project\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 890, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Automation\\test_automation_final_project\\test_cases\\conftest.py\", line 34, in init_driver\n    edriver = get_driver()\n              ^^^^^^^^^^^^\n  File \"C:\\Automation\\test_automation_final_project\\test_cases\\conftest.py\", line 118, in get_driver\n    driver = get_chrome()\n             ^^^^^^^^^^^^\n  File \"C:\\Automation\\test_automation_final_project\\test_cases\\conftest.py\", line 144, in get_chrome\n    chrome_driver = selenium.webdriver.Chrome(service=srv)\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","steps":[],"attachments":[],"parameters":[],"attachmentStep":false,"stepsCount":0,"hasContent":true,"shouldDisplayMessage":true,"attachmentsCount":0}],"afterStages":[{"name":"init_database_connection::0","time":{"start":1726496781463,"stop":1726496781464,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"attachmentStep":false,"stepsCount":0,"hasContent":false,"shouldDisplayMessage":false,"attachmentsCount":0}],"labels":[{"name":"tag","value":"@pytest.mark.usefixtures('init_database_connection')"},{"name":"parentSuite","value":"test_cases"},{"name":"suite","value":"test_cases_db"},{"name":"subSuite","value":"TestCasesDB"},{"name":"host","value":"DESKTOP-1SRCFM0"},{"name":"thread","value":"19216-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"test_cases.test_cases_db"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":true,"retry":true,"extra":{"categories":[],"tags":["@pytest.mark.usefixtures('init_database_connection')"]},"source":"461063ab82b5fd3c.json","parameterValues":[]}